# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provider "virtualbox" do |v|
	 v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.network :forwarded_port, guest: 8081, host: 8081                    # bcom's port
  config.vm.network :forwarded_port, guest: 8080, host: 8080                  # mcom's port
  config.vm.network :forwarded_port, guest: 35729, host: 35729                # livereload port
  config.vm.network :forwarded_port, guest: 5858, host: 5858                  # node debug (node-inspector)
  config.vm.network :forwarded_port, guest: 1337, host: 1337                  # node debug (node-inspector)
  config.vm.network :forwarded_port, guest: 8082, host: 8082                  # weinre
  config.vm.provision :shell, :path => "start.sh", :args => "'/vagrant'"

  config.vm.network :public_network
end
