var $$FSR = {
    'timestamp': 'March 8, 2013 @ 1:21 PM',
    'version': '15.3.8',
    'enabled': true,
    'frames': false,
    'sessionreplay': true,
    'auto': true,
    'encode': false,
    //'files': '/mew20/scripts/foresee/',
    'js_files': '/mew20/scripts/foresee/',
    'image_files': '/mew20/images/foresee/',
    'css_files': '/mew20/styles/foresee/',
    'html_files': '/mew20/scripts/foresee/',
    // needs to be set when foresee-transport.swf is not located at 'files'
    //'swf_files': '__swf_files_'
    'id': 'XnN2LQkjLzuDfUly/WsSkA==',
    'definition': 'foresee-surveydef.js',
    'embedded': false,
    'replay_id': 'mobile_macys',
    'attach': false,
    'renderer': 'W3C', // or "ASRECORDED"
    'layout': 'CENTERFIXED', // or "LEFTFIXED" or "LEFTSTRETCH" or "CENTERSTRETCH"
    'pools': [{
        path: '.',
        sp: 100 // CHANGE ONLY WHEN INCLUDING SESSION REPLAY
    }],
    'sites': [{
		name: 'macys',
        path: /\w+-?\w+\.(com|org|edu|gov|net|co\.uk)/
    }, {
		name: 'macys',
        path: '.',
        domain: 'default'
    }],
    storageOption: 'cookie'
};

var FSRCONFIG = {};

// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
if (typeof(FSR) == "undefined") {
(function(config){var n=void 0,p=!0,q=null,t=!1;
(function(T,P){function L(a,b,c){var e=[];if(0<a.length){var f,j,E,h,k=/[\.:\[#]/g,g=[];if(k.test(a))for(var k=a.match(k),i=0;i<k.length;i++){var l=a.indexOf(k[i]);g.push({O:a.substr(0,l),Da:k[i]});a=a.substr(l)}g.push({O:a});a=g[0].O.toUpperCase();for(k=g.length-1;1<=k;k--)i=g[k-1].Da,l=g[k].O,"["==i?j=l.substr(1,l.length-2).split("="):"."==i?E=l.substr(1):"#"==i?f=l.substr(1):":"==i&&(h=parseInt(l.replace(":nth-child(","").replace(")","")));0==a.length&&(a="*");if(c)for(k=b.childNodes.length-1;0<=
k;k--)c=b.childNodes[k],1==c.nodeType&&("*"==a||c.tagName==a)&&e.push(c);else e=M(b.getElementsByTagName(a));if(f||j||E||h)for(k=e.length-1;0<=k;k--)(h&&d.ta(e[k])!=h-1||E&&-1==e[k].className.indexOf(E)||f&&e[k].id!=f||j&&0>e[k].getAttribute(j[0]).indexOf(j[1]))&&e.splice(k,1)}return e}function M(a){var b=[],c,e=0;for(c=b.length=a.length;e<c;e++)b[e]=a[e];return b}function F(a,b){var c,e,d,j,h=m,g,k=b[a];k&&("object"===typeof k&&"function"===typeof k.toJSON)&&(k=k.toJSON(a));"function"===typeof s&&
(k=s.call(b,a,k));switch(typeof k){case "string":return H(k);case "number":return isFinite(k)?""+k:"null";case "boolean":case "null":return""+k;case "object":if(!k)return"null";m+=y;g=[];if("[object Array]"===Object.prototype.toString.apply(k)){j=k.length;for(c=0;c<j;c+=1)g[c]=F(c,k)||"null";d=0===g.length?"[]":m?"[\n"+m+g.join(",\n"+m)+"\n"+h+"]":"["+g.join(",")+"]";m=h;return d}if(s&&"object"===typeof s){j=s.length;for(c=0;c<j;c+=1)"string"===typeof s[c]&&(e=s[c],(d=F(e,k))&&g.push(H(e)+(m?": ":
":")+d))}else for(e in k)Object.prototype.hasOwnProperty.call(k,e)&&(d=F(e,k))&&g.push(H(e)+(m?": ":":")+d);d=0===g.length?"{}":m?"{\n"+m+g.join(",\n"+m)+"\n"+h+"}":"{"+g.join(",")+"}";m=h;return d}}function H(a){I.lastIndex=0;return I.test(a)?'"'+a.replace(I,function(a){var c=Q[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}var d={},l=l=this,o=l.document;d.fa=864E5;d.q=!!o.attachEvent;var z=Object.prototype.hasOwnProperty,u=[],A=t,x,u=[],A=t;
d.d=function(a){return q!==a&&n!==a};d.qa=function(a){for(var b=a.length-1;0<=b;b--)for(var c=b-1;0<=c;c--)a[c]==a[b]&&a.splice(b,1);return a};d.ta=function(a){for(var b=a.parentNode.childNodes,c,e=count=0;(c=b.item(e++))&&c!=a;)1==c.nodeType&&count++;return count};d.L=function(a){return"[object Array]"==Object.prototype.toString.call(a)};d.ca=function(a){if(a){if(a.length)for(var b=a.length-1;0<=b;b--)a[b]=q;for(var c in a)if(b=typeof a[c],"function"==b||"object"==b)a[c]=q}};d.p=function(a){return"function"==
typeof a};d.ya=function(a){return"object"==typeof a};d.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};d.Ya=function(a){var b=a.getAttribute?a.getAttribute("id"):a.id;b&&!d.cb(b)&&(b=a.attributes.id.value);return b};d.ua=function(a){return a.toString().replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};d.i=function(){var a=arguments,b=a[0]||{},c=1,e=a.length,f,j,g;"object"!==typeof b&&!d.p(b)&&(b={});e===c&&(b=this,--c);for(;c<e;c++)if((f=a[c])!=q)for(j in f)g=f[j],b!==
g&&g!==n&&(b[j]=g);return b};d.w=function(){};d.now=function(){return+new Date};d.shift=function(a){return a.splice(0,1)[0]};d.W=function(a,b){for(var c in b)if(b[c]===a)return c;return-1};d.X=function(){return o.location.protocol};d.ab=function(a,b){return-1!=d.W(a,b)};d.Va=function(a){return o.getElementById(a)};d.Wa=function(a,b,c){for(var e=a.split("."),b=b[d.shift(e)],f=c,j;b!=q&&0<e.length;)b=b[d.shift(e)];if(b){for(e=a.split(".");e.length&&(j=d.shift(e));)f=f[j]?f[j]:f[j]={};e=a.split(".");
for(f=c;e.length&&(j=d.shift(e));)0<e.length?f=f[j]:f[j]=b}};d.M=function(){return o.location.href};d.t=function(a){return encodeURIComponent(a)};d.G=function(a){return decodeURIComponent(a)};d.ra=function(){return o.referrer};d.eb={};d.za=function(a,b){var b=b||d.w,c=o.createElement("script");c.type="text/javascript";d.q?c.onreadystatechange=function(){("loaded"==this.readyState||"complete"==this.readyState)&&b("ok")}:c.onload=function(){b("ok")};c.onerror=function(){b("error")};c.src=0==d.W("//",
a)?d.X()+a:a;d.T.appendChild(c)};d.l=function(a,b,c){c||(c=l);c=c.document;c=c.readyState;b=b||1;if(d.p(a)&&(a=function(a,b){return function(){setTimeout(function(a){return function(){a.call(d.D);a=q}}(a),b);a=q}}(a,b),c&&("complete"==c||"loaded"==c))){A=p;for(u.push(a);a=d.shift(u);)a&&a.call(d.D);return}if(!A&&d.p(a))u.push(a);else if(A&&d.p(a))a.call(d.D);else if(!d.p(a))for(A=p;0<u.length;)(a=d.shift(u))&&a.call(d.D);a=c=c=c=q};o.addEventListener?x=function(){-1<"complete,loaded".indexOf(o.readyState)&&
(o.removeEventListener("readystatechange",x,t),d.l(q))}:d.q&&(x=function(){-1<"complete,loaded".indexOf(o.readyState)&&(o.detachEvent("onreadystatechange",x),d.l(q))});t||(o.addEventListener?(o.addEventListener("readystatechange",x,t),o.addEventListener("DOMContentLoaded",d.l,t)):d.q&&o.attachEvent("onreadystatechange",x));d.match=function(a){for(var b=[["urls",d.M()],["referrers",d.ra()],["userAgents",l.navigator.userAgent],["browsers",{name:BROWSER.Ua,version:BROWSER.Pa}]],c=0;c<b.length;c++)for(var e=
b[c],f=a[e[0]]||[],j=0;j<f.length;j++){var g=f[j];if(d.ya(e[1])){if(d.G(e[1].name.toLowerCase()).match(g.name.toLowerCase())&&(!g.version||e[1].version==g.version))return p}else if(d.G(e[1]).match(g))return p}f=a.cookies||[];for(c=0;c<f.length;c++){e=f[c];if(b=h.a.ba(e.name))if(b.match(e.value||"."))return p}c=h.e("fsr.ipo",h.c("fsr.ipo"));if(a=a.variables){e=0;for(f=a.length;e<f;e++){j=a[e].name;b=a[e].value;if(!(j==G.ipexclude&&c.get("value")==1)){if(!d.L(j)){j=[j];b=[b]}for(var i,g=p,k=0,o=j.length;k<
o;k++){try{i=(new Function("return "+j[k]))();if(i===n||i===q)i=""}catch(r){i=""}var m;if(m=i||i===""){a:{m=i;var s=b[k];d.L(s)||(s=[s]);for(var u=0,v=s.length;u<v;u++)if((m+"").match(s[u])){m=p;break a}m=t}m=!m}if(m){g=t;break}}if(g)return p}}}return t};d.T=q;d.l(function(){d.T=o.getElementsByTagName("head")[0]||o.documentElement});d.startTime=d.now();var G={},g=d.i({replay_id:"sitecom",site:{domain:"site.com"},renderer:"W3C",layout:"",swf_files:"/"},P||{});d.Ba=function(){for(var a={},b=arguments,
c=0,e=b.length;c<e;c++){var f=b[c];if(d.v(f))for(var j in f){var g=f[j],h=a[j];a[j]=h&&d.v(g)&&d.v(h)?d.Ba(h,g):d.Q(g)}}return a};d.Q=function(a){var b;if(d.v(a)){b={};for(var c in a)b[c]=d.Q(a[c])}else if(d.L(a)){b=[];c=0;for(var e=a.length;c<e;c++)b[c]=d.Q(a[c])}else b=a;return b};d.v=function(a){if(!a||(Object.prototype.toString.call(a)!=="[object Object]"||a.nodeType||a.setInterval)||a.constructor&&!z.call(a,"constructor")&&!z.call(a.constructor.prototype,"isPrototypeOf"))return t;for(var b in a);
return b===n||z.call(a,b)||!z.call(a,b)&&z.call(Object.prototype,b)};d.H=function(){u=g=q;d=l=l.FSR=q};d.$a=function(a){var b=d.now(),c;do c=d.now();while(c-b<a)};if(d.d(l.FSRCONFIG)){var r=l.FSRCONFIG;r.surveydefs&&(d.surveydefs=r.surveydefs,r.surveydefs=q);r.properties&&(d.properties=r.properties,r.properties=q)}l.FSR=d;l.FSR.opts=g;l.FSR.prop=G;d.g={};d.g.na={};var i=d.g.na;i.Xa=function(){for(var a=BROWSER.Sa.replace(/[\s\\\/\.\(\);:]/gim,""),b="",c=d.now()+"",e=0;e<a.length-1;e=e+a.length/7)b=
b+Number(a.charCodeAt(Math.round(e))%16).toString(16);b.length>7&&(b=b.substr(b.length-7));return b+"-"+a.length+c.substr(c.length-6)+"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a=="x"?b:b&3|8).toString(16)})};i.hb=function(a,b){return a+Math.random()*(b-a)};i.Ga=function(a){var b="";if(a)for(var c in a)b=b+((b.length!=0?"&":"")+c+"="+d.t(a[c]));return b};i.hash=function(a){a=a.split("_");return a[0]*3+1357+""+(a[1]*9+58)};i.gb=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,
"\\]");a=RegExp("[\\?&+]"+a+"=([^&#]*)").exec(d.M());return a==q?t:a[1]};i.sa=function(a){return a.js_files||a.files};i.Ra=function(a,b){for(var c=0;c<document.styleSheets.length;c++)if(!document.styleSheets[c].href||document.styleSheets[c].href.indexOf("foresee-dhtml.css")==-1){var e=document.styleSheets[c].cssRules?document.styleSheets[c].cssRules:document.styleSheets[c].rules;if(e)for(var d=0;d<e.length;d++)e[d].cssText&&(e[d].cssText.match(a)&&e[d].selectorText)&&R(N(e[d].selectorText),b)}};d.g.ha=
{};var v=d.g.ha;d.g.ea={};r=d.g.ea;r.Qa=function(a,b){var c,e,f;d.d(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++){f=a[c];var j=f.className||"";if(!RegExp("\\b"+b+"\\b").test(j))f.className=(j==""?"":j+" ")+b}};r.ib=function(a,b){var c,e,f;d.d(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++){f=a[c];if(f.className)f.className=f.className.replace(RegExp("\\b"+b+"\\b"),"")}};r.pa=function(a,b){if(a){d.d(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in b)if(e){"zIndex".indexOf(e)==-1&&(typeof b[e]==
"number"&&e!="opacity")&&(b[e]=b[e]+"px");a[c].style[e]=b[e]}}return a};r.Ta=function(a,b){if(a){d.d(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in b)a[c].setAttribute(e,b[e])}return a};var R=r.pa;r.outerHTML=function(a){if(d.d(a.outerHTML))return a.outerHTML;var b={TEXTAREA:p},c={HR:p,BR:p,IMG:p,INPUT:p},e=[],f="",j=a.nodeName;switch(a.nodeType){case 1:f=f+"<"+j.toLowerCase();if(b[j])switch(j){case "TEXTAREA":for(b=0;b<a.attributes.length;b++)if(a.attributes[b].nodeName.toLowerCase()!=
"value")f=f+(" "+a.attributes[b].nodeName.toUpperCase()+'="'+a.attributes[b].nodeValue+'"');else var g=a.attributes[b].nodeValue;f=f+">"+g+("</"+j+">")}else{for(b=a.attributes.length-1;b>=0;b--){g=a.attributes[b].nodeName.toLowerCase();"style,class,id".indexOf(g.toLowerCase())>-1&&(f=f+(" "+g+'="'+a.attributes[b].nodeValue+'"'))}f=f+">";if(!c[j]){f=f+a.innerHTML;f=f+("</"+j.toLowerCase()+">")}}break;case 3:f=f+a.nodeValue;break;case 8:f=f+("<\!--"+a.nodeValue+"--\>")}e.push(f);return e.join("")};
for(var J={},B=["onload","onerror","onabort"],w=0;w<B.length;w++)J[B[w]]=function(){this.Ca(arguments.callee.xa==0?1:0);this.z=t},J[B[w]].xa=w;v.k=function(a,b){this.options=d.i({},a);this.z=t;this.event=b;this.R=0;return this};v.k.prototype.Ca=function(a){if(this.z){this.z=t;this.status=a;switch(a){case 1:(this.options.onSuccess||d.w)(n);break;case 0:this.event?this.Ha():(this.options.onFailure||d.w)(n);break;case -1:(this.options.onError||d.w)(n)}}};v.k.prototype.Ha=function(){if(this.R<3)this.V();
else this.onFailure()};v.k.prototype.oa=function(a){var b;this.z=p;a=i.Ga(d.i(a,{uid:d.now()}));a=d.X()+"//"+this.options.host+this.options.path+this.options.url+"?"+a;b=d.i({},J,b);for(var c=new Image,e=0;e<B.length;e++){var f=B[e];c[f]=function(){var a=arguments.callee;a.o.onload=a.o.onerror=a.o.onabort=q;a.wa.call(a.self,a.o);a.o=q};c[f].wa=b[f];c[f].o=c;c[f].self=this}c.src=a};v.k.prototype.send=function(a){this.Ia=a;this.V()};v.k.prototype.V=function(){var a;this.R++;a=d.i({event:this.event,
ver:this.R},this.Ia,a);this.oa(a)};d.g.ja={};var h=d.g.ja;h.u=function(a){return a+(g.site.cookie?"."+g.site.cookie:"")};h.J=function(a){var b=h.u("fsr.s"),b=h.e(b,h.c(b));return a?d.d(n)?b.set(a,n):b.get(a):b};h.c=function(a,b){var c;c=g.storageOption=="window"?function(){var a=arguments.callee;return new h.Na(a.aa,a.Y||{})}:function(){var a=arguments.callee;return new h.a(a.aa,d.i({path:"/",domain:a.N.site.domain,secure:a.N.site.secure,encode:a.N.encode},a.Y||{}))};c.aa=a;c.N=g;c.Y=b;return c};
var O={};h.e=function(a,b){var c=O[a];if(c!=q)return c;return c=O[a]=new b};i.b={};i.b.m={};i.b.A=function(a,b,c,e){var f=i.b.m;if(a){f[b]||(f[b]=[]);f[b].push({I:a,C:c});if(b=="unload"){if(d.d(d.s)){d.s.push(c);return}d.s=[]}b!="propertychange"&&a.addEventListener?a.addEventListener(b,c,!e):a.attachEvent&&a.attachEvent("on"+b,c)}};i.b.Ja=function(a,b,c,e,f){var g=i.b;if(f){if(a.getAttribute("_fsr"+b))return t;a.setAttribute("_fsr"+b,"true")}else if(f=g.m[b])for(g=f.length-1;g>=0;g--){if(d.q)try{f[g].I.toString()}catch(h){f.splice(g,
1);continue}if(f[g].I==a&&(e||f[g].C==c))return t}i.b.A(a,b,c)};i.b.Ka=function(a,b,c){i.b.A(a,b,c,p)};i.b.ma=function(a,b,c){try{b!="propertychange"&&a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)}catch(d){}};w=i.b.A;i.b.ga=function(){for(var a=d.s.length-1;a>=0;a--)try{d.s[a].call()}catch(b){}d.ca(d.s);i.b.ia();d.H()};w(l,"unload",i.b.ga);i.b.ia=function(){if(d){var a=i.b,b;for(b in a.m){for(var c=a.m[b],e={};e=c.pop();){a.ma(e.I,b,e.C);d.ca(e)}delete a.m[b]}}};
i.b.S=function(){this.P=[]};i.b.S.prototype.va=function(){for(var a=0;a<this.P.length;a++){var b=this.P[a];b.C.apply(this,arguments);if(b.fb){this.P.splice(a,1);a--}}};var S=i.b.S,C={};d.stringify=function(a,b,c){var d;if(l.Prototype){d=Array.prototype.toJSON;delete Array.prototype.toJSON}if(!l.JSON||typeof l.JSON.stringify!=="function"){var f;y=m="";if(typeof c==="number")for(f=0;f<c;f=f+1)y=y+" ";else typeof c==="string"&&(y=c);if((s=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!==
"number"))throw Error("_4c.stringify");a=F("",{"":a})}else a=l.JSON.stringify(a,b,c);if(l.Prototype)Array.prototype.toJSON=d;return a};var K=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,I=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m,y,Q={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},s;l.JSON?C=l.JSON:function(){function a(a){return a<
10?"0"+a:a}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":q};Boolean.prototype.toJSON=function(){return this.valueOf()};Number.prototype.toJSON=function(){return this.valueOf()};String.prototype.toJSON=function(){return this.valueOf()}}if(typeof C.parse!=="function")C.parse=function(a,
c){function d(a,b){var f,g,h=a[b];if(h&&typeof h==="object")for(f in h)if(Object.prototype.hasOwnProperty.call(h,f)){g=d(h,f);g!==n?h[f]=g:delete h[f]}return c.call(a,b,h)}var f,a=""+a;K.lastIndex=0;K.test(a)&&(a=a.replace(K,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){f=(new Function("return "+
a))();return typeof c==="function"?d({"":f},""):f}throw new SyntaxError("JSON.parse");}}();i.La=C;r.U={Oa:{}};try{Array.prototype.slice.call(document.getElementsByTagName("html")),makeArray=function(a){return Array.prototype.slice.call(a)}}catch(U){}var N=r.U.jb=function(a,b,c){b=b||o;if(b.querySelectorAll&&(!d.q||!(BROWSER.version<=8&&a.indexOf("nth")>-1)))return M(b.querySelectorAll(a));if(!c&&l.$&&!l.Prototype)return l.$(a,b);for(var a=a.split(","),c=[],e=a.length-1;e>=0;e--){var f=a[e].replace(/^\s\s*/,
"").replace(/\s\s*$/,"").replace(/\*=/g,"=").replace(/\>/g," > ").replace(/\s+/g," ");if(f.indexOf(" ")>-1){for(var f=f.split(" "),g=[b],h=t,i=0;i<f.length;i++)if(f[i]==">")h=p;else{for(var k=[],m=g.length-1;m>=0;m--)k=k.concat(L(f[i],g[m],h));g=k;h=t}c=c.concat(d.qa(g))}else c=c.concat(L(f,b))}return c};h.a=function(a,b){a||(a="STORAGE");this.K=a.replace(/[- ]/g,"");this.r=b||{};this.data={};this.ka=new S;this.Fa=4E3};h.a.prototype.set=function(a,b){this.B();this.h[a]=b;this.F()};h.a.prototype.get=
function(a){this.B();return a?this.h[a]:this.h};h.a.prototype.H=function(a){this.B();delete this.h[a];this.F()};h.a.prototype.j=function(){this.h={};var a=this.r.duration;this.r.duration=-1;this.F();a?this.r.duration=a:delete this.r.duration};h.a.prototype.B=function(){this.h={};try{var a=h.a.ba(this.K);if(a&&a.length>0){this.h=C.parse(a);if(!d.d(this.h))this.h={}}}catch(b){this.h={}}};h.a.prototype.F=function(){var a=d.stringify(this.h);this.K.length+d.t(a).length>this.Fa&&this.ka.va(this);h.a.write(this.K,
a,this.r)};h.a.ba=function(a){return(a=l.document.cookie.match("(?:^|;)\\s*"+d.ua(a)+"=([^;]*)"))?d.G(a[1]):q};h.a.write=function(a,b,c){var b=!c||!d.d(c.encode)||c.encode?d.t(b):b,a=d.t(a),e;for(e in c)if(c[e]){var f=c[e],b=b+(";"+(e==="duration"?"expires":e));switch(e){case "duration":b=b+("="+(new Date(d.now()+f*d.fa)).toGMTString());default:b=b+("="+f)}}l.document.cookie=a+"="+b;return a.length+b.length+2};h.a.j=function(a,b){h.a.write(a,"",d.i(b,{duration:-1}))};h.a.bb=function(){};h.a.isSupported=
function(){return p};d.g.la={};var D=d.g.la;D.Za=function(a,b){for(var c=a.name,d=[a.site,a.section,b,h.J("q"),h.J("l")],f=0;f<d.length;f++)c=c+(d[f]?"-"+d[f]:"");return c};D.Aa=function(a,b){function c(b){if("ok"===b&&d.surveydefs){d.i(G,d.properties);g.da=g.surveydefs=d.surveydefs;a()}}var e=g.definition||"foresee-surveydef.js";b?setTimeout(function(){c("ok")},100):d.za(i.sa(g.site)+e,c)};D.log=function(a,b){if(G.events.enabled){var c=h.J(),e=c.get("sd");d.d(e)||(e=c.get("cd"));var e=g.da[e],f=
new Date;(new v.k(D.Ma.event,"logit")).send({cid:g.id,rid:c.get("rid")||"",cat:e.name,sec:e.section||"",type:c.get("q")||"",site:g.site.name||"",lang:c.get("l")||d.$S.locale||"",msg:a,param:b,tms:f.getTime(),tmz:f.getTimezoneOffset()*6E4})}};N=r.U;d.l(function(){for(var a=g.sites,b=0,c=a.length;b<c;b++){var e;typeof a[b].path!=="[object Array]"&&(a[b].path=[a[b].path]);for(var f=0,h=a[b].path.length;f<h;f++)if(e=d.M().match(a[b].path[f])){g.siteid=b;g.site=g.sites[b];g.site.domain?g.site.domain==
"default"&&(g.site.domain=q):g.site.domain=e[0];g.site.secure||(g.site.secure=q);g.site.name||(g.site.name=e[0]);f=["files","js_files","image_files","html_files","css_files","swf_files"];for(b=0;b<f.length;b++)g.site[f[b]]||g[f[b]]&&(g.site[f[b]]=g[f[b]]);break}if(e)break}});d.f=function(a){d.i(this,{options:d.i({},a)});g.controller=this};d.f.prototype.load=function(){var a=this;D.Aa(function(){a.Ea()},g.embedded)};d.f.n=function(a){for(var b=document.getElementsByTagName("input"),c=[],d=0;d<b.length;d++)b[d].type==
a.type&&(a.name?b[d].name==a.name&&c.push(b[d]):c.push(b[d]));return c};d.f.prototype.Ea=function(){for(var a=h.e("fsr.sp",h.c("fsr.sp")),b=[],c=g.da,e=0;e<c.length;e++)if(!(c[e].site&&c[e].site!=g.site.name)){var f=c[e].criteria;if(d.d(f.sp)){var j=n;b.push(this.Z(c[e].name,c[e].section||j,n,a,f.sp,f.lf))}for(var f=f.locales||[],i=0,l=f.length;i<l;i++){j=n;b.push(this.Z(c[e].name,c[e].section||j,f[i].locale,a,f[i].sp,f[i].lf))}}e='<table><tr><td class="names">&nbsp;</td><td colspan="2">Sampling Percentage</td><td>&nbsp;</td><td>Loyalty Factor</td></tr>';
a=0;for(c=b.length;a<c;a++){j=b[a];f=j.input;e=e+"<tr>";e=e+('<td class="names">'+j.names+"</td>");e=e+('<td><input type="text" name="'+f.name+'" value="'+f.value+'" size="'+f.size+'" maxlength="'+f.maxlength+'"></td>');e=e+("<td>"+j.percentage+"</td>");e=e+"<td>&nbsp;</td>";e=e+("<td>"+j.loyaltyFactor+"</td>");e=e+"</tr>"}document.getElementById("controls").innerHTML=e+"</table>";if(h.e("fsr.ipo",h.c("fsr.ipo")).get("value")==1){b=d.f.n({type:"checkbox",name:"ipo"});for(e=0;e<b.length;e++)b.checked=
p}if(h.e("fsr.pool",h.c("fsr.pool")).get("value")==1){b=d.f.n({type:"checkbox",name:"pool"});for(e=0;e<b.length;e++)b.checked=p}};d.f.prototype.Z=function(a,b,c,d,f,g){var h=a;if(b){h=h+("-"+b);a=a+("-"+b)}if(c){h=h+(" ("+c+")");a=a+("-"+c)}return{names:h+":",input:{name:a,value:d.get(a)||"",size:3,maxlength:3},percentage:"("+f+")",loyaltyFactor:g}};d.f.prototype.set=function(){for(var a=d.f,b=h.e("fsr.sp",h.c("fsr.sp",{duration:1})),c=a.n({type:"text"}),e=0;e<c.length;e++){var f=c[e];f.value!=""?
b.set(f.name,f.value):b.H(f.name)}b=a.n({type:"checkbox",name:"ipo"})[0];a=a.n({type:"checkbox",name:"pool"})[0];b.checked?h.e("fsr.ipo",h.c("fsr.ipo")).set("value",b.checked?1:0):h.e("fsr.ipo",h.c("fsr.ipo")).j();a.checked?h.e("fsr.pool",h.c("fsr.pool")).set("value",a.checked?1:0):h.e("fsr.pool",h.c("fsr.pool")).j()};d.f.prototype.clear=function(){var a=h,b=a.e;b("fsr.sp",h.c("fsr.sp")).j();b("fsr.ipo",a.c("fsr.ipo")).j();b("fsr.pool",a.c("fsr.pool")).j();a.a.j(a.u("fsr.r"),{path:"/",domain:g.site.domain,
secure:g.site.secure});a.a.j(a.u("fsr.s"),{path:"/",domain:g.site.domain,secure:g.site.secure});a.a.j(a.u("fsr.p"),{path:"/",domain:g.site.domain,secure:g.site.secure});a=document.getElementsByTagName("input");for(b=0;b<a.length;b++){var c=a[b];if(c.type=="text")c.value="";else if(c.type=="checkbox")c.checked=t}};d.l(function(){var a=new d.f;g.controller.set=a.set;g.controller.clear=a.clear;a.load()})})(window,$$FSR);})({});
}
// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
