var $$FSR = {
    'timestamp': 'March 8, 2013 @ 1:21 PM',
    'version': '15.3.8',
    'enabled': true,
    'frames': false,
    'sessionreplay': true,
    'auto': true,
    'encode': false,
    //'files': '/mew20/scripts/foresee/',
    'js_files': '/mew20/scripts/foresee/',
    'image_files': '/mew20/images/foresee/',
    'css_files': '/mew20/styles/foresee/',
    'html_files': '/mew20/scripts/foresee/',
    // needs to be set when foresee-transport.swf is not located at 'files'
    //'swf_files': '__swf_files_'
    'id': 'XnN2LQkjLzuDfUly/WsSkA==',
    'definition': 'foresee-surveydef.js',
    'embedded': false,
    'replay_id': 'mobile_macys',
    'attach': false,
    'renderer': 'W3C', // or "ASRECORDED"
    'layout': 'CENTERFIXED', // or "LEFTFIXED" or "LEFTSTRETCH" or "CENTERSTRETCH"
    'pools': [{
        path: '.',
        sp: 100 // CHANGE ONLY WHEN INCLUDING SESSION REPLAY
    }],
    'sites': [{
		name: 'macys',
        path: /\w+-?\w+\.(com|org|edu|gov|net|co\.uk)/
    }, {
		name: 'macys',
        path: '.',
        domain: 'default'
    }],
    storageOption: 'cookie'
};

var FSRCONFIG = {};

// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
if (typeof(FSR) == "undefined") {
(function(config){var o=void 0,r=!0,s=null,w=!1;function y(){return function(){}}
(function(Z,U){function u(a,b){return(b?a.get(b):a)||""}function K(a){return[a||h.e(),(a||h.e()).get("cp")||{}]}function R(a,b,c){var f=[];if(0<a.length){var e,m,h,g,k=/[\.:\[#]/g,i=[];if(k.test(a))for(var k=a.match(k),j=0;j<k.length;j++){var l=a.indexOf(k[j]);i.push({ha:a.substr(0,l),wb:k[j]});a=a.substr(l)}i.push({ha:a});a=i[0].ha.toUpperCase();for(k=i.length-1;1<=k;k--)j=i[k-1].wb,l=i[k].ha,"["==j?m=l.substr(1,l.length-2).split("="):"."==j?h=l.substr(1):"#"==j?e=l.substr(1):":"==j&&(g=parseInt(l.replace(":nth-child(",
"").replace(")","")));0==a.length&&(a="*");if(c)for(k=b.childNodes.length-1;0<=k;k--)c=b.childNodes[k],1==c.nodeType&&("*"==a||c.tagName==a)&&f.push(c);else f=S(b.getElementsByTagName(a));if(e||m||h||g)for(k=f.length-1;0<=k;k--)(g&&d.ab(f[k])!=g-1||h&&-1==f[k].className.indexOf(h)||e&&f[k].id!=e||m&&0>f[k].getAttribute(m[0]).indexOf(m[1]))&&f.splice(k,1)}return f}function S(a){var b=[],c,d=0;for(c=b.length=a.length;d<c;d++)b[d]=a[d];return b}function V(a,b){var c=[],d;for(d in a)a.hasOwnProperty(d)&&
(c[d]=b(a[d]));return c}function L(a,b){var c,d,e,m,h=q,g,k=b[a];k&&("object"===typeof k&&"function"===typeof k.toJSON)&&(k=k.toJSON(a));"function"===typeof x&&(k=x.call(b,a,k));switch(typeof k){case "string":return N(k);case "number":return isFinite(k)?""+k:"null";case "boolean":case "null":return""+k;case "object":if(!k)return"null";q+=E;g=[];if("[object Array]"===Object.prototype.toString.apply(k)){m=k.length;for(c=0;c<m;c+=1)g[c]=L(c,k)||"null";e=0===g.length?"[]":q?"[\n"+q+g.join(",\n"+q)+"\n"+
h+"]":"["+g.join(",")+"]";q=h;return e}if(x&&"object"===typeof x){m=x.length;for(c=0;c<m;c+=1)"string"===typeof x[c]&&(d=x[c],(e=L(d,k))&&g.push(N(d)+(q?": ":":")+e))}else for(d in k)Object.prototype.hasOwnProperty.call(k,d)&&(e=L(d,k))&&g.push(N(d)+(q?": ":":")+e);e=0===g.length?"{}":q?"{\n"+q+g.join(",\n"+q)+"\n"+h+"}":"{"+g.join(",")+"}";q=h;return e}}function N(a){O.lastIndex=0;return O.test(a)?'"'+a.replace(O,function(a){var c=W[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}var d={},g=g=this,p=g.document;d.na=864E5;d.t=!!p.attachEvent;var F=Object.prototype.hasOwnProperty,z=[],G=w,C,z=[],G=w;d.l=function(a){return s!==a&&o!==a};d.Za=function(a){for(var b=a.length-1;0<=b;b--)for(var c=b-1;0<=c;c--)a[c]==a[b]&&a.splice(b,1);return a};d.ab=function(a){for(var b=a.parentNode.childNodes,c,d=count=0;(c=b.item(d++))&&c!=a;)1==c.nodeType&&count++;return count};d.da=function(a){return"[object Array]"==Object.prototype.toString.call(a)};d.Fa=function(a){if(a){if(a.length)for(var b=
a.length-1;0<=b;b--)a[b]=s;for(var c in a)if(b=typeof a[c],"function"==b||"object"==b)a[c]=s}};d.v=function(a){return"function"==typeof a};d.lb=function(a){return"object"==typeof a};d.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};d.Vb=function(a){var b=a.getAttribute?a.getAttribute("id"):a.id;b&&!d.$b(b)&&(b=a.attributes.id.value);return b};d.bb=function(a){return a.toString().replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};d.k=function(){var a=arguments,b=a[0]||{},
c=1,f=a.length,e,m,g;"object"!==typeof b&&!d.v(b)&&(b={});f===c&&(b=this,--c);for(;c<f;c++)if((e=a[c])!=s)for(m in e)g=e[m],b!==g&&g!==o&&(b[m]=g);return b};d.Q=y();d.now=function(){return+new Date};d.shift=function(a){return a.splice(0,1)[0]};d.ta=function(a,b){for(var c in b)if(b[c]===a)return c;return-1};d.Z=function(){return p.location.protocol};d.Xb=function(a,b){return-1!=d.ta(a,b)};d.Pb=function(a){return p.getElementById(a)};d.Rb=function(a,b,c){for(var f=a.split("."),b=b[d.shift(f)],e=c,
m;b!=s&&0<f.length;)b=b[d.shift(f)];if(b){for(f=a.split(".");f.length&&(m=d.shift(f));)e=e[m]?e[m]:e[m]={};f=a.split(".");for(e=c;f.length&&(m=d.shift(f));)0<f.length?e=e[m]:e[m]=b}};d.Ba=function(){return p.location.href};d.N=function(a){return encodeURIComponent(a)};d.X=function(a){return decodeURIComponent(a)};d.$a=function(){return p.referrer};d.ac={};d.pb=function(a,b){var b=b||d.Q,c=p.createElement("script");c.type="text/javascript";d.t?c.onreadystatechange=function(){("loaded"==this.readyState||
"complete"==this.readyState)&&b("ok")}:c.onload=function(){b("ok")};c.onerror=function(){b("error")};c.src=0==d.ta("//",a)?d.Z()+a:a;d.oa.appendChild(c)};d.w=function(a,b,c){c||(c=g);c=c.document;c=c.readyState;b=b||1;if(d.v(a)&&(a=function(a,b){return function(){setTimeout(function(a){return function(){a.call(d.V);a=s}}(a),b);a=s}}(a,b),c&&("complete"==c||"loaded"==c))){G=r;for(z.push(a);a=d.shift(z);)a&&a.call(d.V);return}if(!G&&d.v(a))z.push(a);else if(G&&d.v(a))a.call(d.V);else if(!d.v(a))for(G=
r;0<z.length;)(a=d.shift(z))&&a.call(d.V);a=c=c=c=s};p.addEventListener?C=function(){-1<"complete,loaded".indexOf(p.readyState)&&(p.removeEventListener("readystatechange",C,w),d.w(s))}:d.t&&(C=function(){-1<"complete,loaded".indexOf(p.readyState)&&(p.detachEvent("onreadystatechange",C),d.w(s))});w||(p.addEventListener?(p.addEventListener("readystatechange",C,w),p.addEventListener("DOMContentLoaded",d.w,w)):d.t&&p.attachEvent("onreadystatechange",C));d.match=function(a){for(var b=[["urls",d.Ba()],
["referrers",d.$a()],["userAgents",g.navigator.userAgent],["browsers",{name:t.j,version:t.ra}]],c=0;c<b.length;c++)for(var f=b[c],e=a[f[0]]||[],m=0;m<e.length;m++){var i=e[m];if(d.lb(f[1])){if(d.X(f[1].name.toLowerCase()).match(i.name.toLowerCase())&&(!i.version||f[1].version==i.version))return r}else if(d.X(f[1]).match(i))return r}e=a.cookies||[];for(c=0;c<e.length;c++){f=e[c];if(b=h.h.I(f.name))if(b.match(f.value||"."))return r}c=h.pa("fsr.ipo",h.Aa("fsr.ipo"));if(a=a.variables){f=0;for(e=a.length;f<
e;f++){m=a[f].name;b=a[f].value;if(!(m==v.ipexclude&&c.get("value")==1)){if(!d.da(m)){m=[m];b=[b]}for(var j,i=r,k=0,l=m.length;k<l;k++){try{j=(new Function("return "+m[k]))();if(j===o||j===s)j=""}catch(n){j=""}var p;if(p=j||j===""){a:{p=j;var q=b[k];d.da(q)||(q=[q]);for(var u=0,x=q.length;u<x;u++)if((p+"").match(q[u])){p=r;break a}p=w}p=!p}if(p){i=w;break}}if(i)return r}}}return w};d.oa=s;d.w(function(){d.oa=p.getElementsByTagName("head")[0]||p.documentElement});d.startTime=d.now();var v={},i=d.k({replay_id:"sitecom",
site:{domain:"site.com"},renderer:"W3C",layout:"",swf_files:"/"},U||{});d.G=function(){for(var a={},b=arguments,c=0,f=b.length;c<f;c++){var e=b[c];if(d.O(e))for(var m in e){var g=e[m],h=a[m];a[m]=h&&d.O(g)&&d.O(h)?d.G(h,g):d.ja(g)}}return a};d.ja=function(a){var b;if(d.O(a)){b={};for(var c in a)b[c]=d.ja(a[c])}else if(d.da(a)){b=[];c=0;for(var f=a.length;c<f;c++)b[c]=d.ja(a[c])}else b=a;return b};d.O=function(a){if(!a||(Object.prototype.toString.call(a)!=="[object Object]"||a.nodeType||a.setInterval)||
a.constructor&&!F.call(a,"constructor")&&!F.call(a.constructor.prototype,"isPrototypeOf"))return w;for(var b in a);return b===o||F.call(a,b)||!F.call(a,b)&&F.call(Object.prototype,b)};d.Y=function(){z=i=s;d=g=g.FSR=s};d.Wb=function(a){var b=d.now(),c;do c=d.now();while(c-b<a)};if(d.l(g.FSRCONFIG)){var n=g.FSRCONFIG;n.surveydefs&&(d.surveydefs=n.surveydefs,n.surveydefs=s);n.properties&&(d.properties=n.properties,n.properties=s)}g.FSR=d;g.FSR.opts=i;g.FSR.prop=v;d.n={};d.n.Ma={};var A=d.n.Ma;d.n.Ta=
{};var l=d.n.Ta;l.Tb=function(){for(var a=t.sa.replace(/[\s\\\/\.\(\);:]/gim,""),b="",c=d.now()+"",f=0;f<a.length-1;f=f+a.length/7)b=b+Number(a.charCodeAt(Math.round(f))%16).toString(16);b.length>7&&(b=b.substr(b.length-7));return b+"-"+a.length+c.substr(c.length-6)+"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a=="x"?b:b&3|8).toString(16)})};l.ec=function(a,b){return a+Math.random()*(b-a)};l.r=function(a,b,c){var f="";if(a)for(var e in a)f=f+((f.length!=0?"&":"")+
(b?b+"["+e+"]":e)+"="+(c?a[e]:d.N(a[e])));return f};l.hash=function(a){a=a.split("_");return a[0]*3+1357+""+(a[1]*9+58)};l.fa=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&+]"+a+"=([^&#]*)").exec(d.Ba());return a==s?w:a[1]};l.va=function(a,b){return a[b]||a.files};l.Nb=function(a,b){for(var c=0;c<document.styleSheets.length;c++)if(!document.styleSheets[c].href||document.styleSheets[c].href.indexOf("foresee-dhtml.css")==-1){var d=document.styleSheets[c].cssRules?document.styleSheets[c].cssRules:
document.styleSheets[c].rules;if(d)for(var e=0;e<d.length;e++)d[e].cssText&&(d[e].cssText.match(a)&&d[e].selectorText)&&X(Y(d[e].selectorText),b)}};for(var P={},H=["onload","onerror","onabort"],n=0;n<H.length;n++)P[H[n]]=function(){this.sb(arguments.callee.jb==0?1:0);this.q=w},P[H[n]].jb=n;A.u=function(a,b){this.options=d.k({},a);this.q=w;this.event=b;this.ka=0;return this};A.u.prototype.sb=function(a){if(this.q){this.q=w;this.status=a;switch(a){case 1:(this.options.onSuccess||d.Q)(o);break;case 0:this.event?
this.Db():(this.options.onFailure||d.Q)(o);break;case -1:(this.options.onError||d.Q)(o)}}};A.u.prototype.Db=function(){if(this.ka<3)this.qa();else this.onFailure()};A.u.prototype.Ua=function(a){var b;this.q=r;a=l.r(d.k(a,{uid:d.now()}));a=d.Z()+"//"+this.options.host+this.options.path+this.options.url+"?"+a;b=d.k({},P,b);for(var c=new Image,f=0;f<H.length;f++){var e=H[f];c[e]=function(){var a=arguments.callee;a.D.onload=a.D.onerror=a.D.onabort=s;a.eb.call(a.self,a.D);a.D=s};c[e].eb=b[e];c[e].D=c;
c[e].self=this}c.src=a};A.u.prototype.send=function(a){this.Fb=a;this.qa()};A.u.prototype.qa=function(){var a;this.ka++;a=d.k({event:this.event,ver:this.ka},this.Fb,a);this.Ua(a)};d.n.Ra={};var j=d.n.Ra;j.gb=function(a,b){for(var c=a.name,d=[a.site,a.section,b,h.e("q"),h.e("l")],e=0;e<d.length;e++)c=c+(d[e]?"-"+d[e]:"");return c};j.qb=function(a,b){function c(b){if("ok"===b&&d.surveydefs){d.k(v,d.properties);i.ia=i.surveydefs=d.surveydefs;a()}}var f=i.definition||"foresee-surveydef.js";b?setTimeout(function(){c("ok")},
100):d.pb(l.va(i.site,"js_files")+f,c)};j.log=function(a,b){if(v.events.enabled){var c=h.e(),f=c.get("sd");d.l(f)||(f=c.get("cd"));var f=i.ia[f],e=new Date;(new A.u(j.p.event,"logit")).send({cid:i.id,rid:c.get("rid")||"",cat:f.name,sec:f.section||"",type:c.get("q")||"",site:i.site.name||"",lang:c.get("l")||d.$S.locale||"",msg:a,param:b,tms:e.getTime(),tmz:e.getTimezoneOffset()*6E4})}};d.n.Pa={};var h=d.n.Pa;h.za=function(a){return a+(i.site.cookie?"."+i.site.cookie:"")};h.e=function(a,b){var c=h.za("fsr.s"),
c=h.pa(c,h.Aa(c));return a?d.l(b)?c.set(a,b):c.get(a):c};h.Aa=function(a){var b;b=i.storageOption=="window"?function(){var a=arguments.callee;return new h.Kb(a.Ca,a.xa||{})}:function(){var a=arguments.callee;return new h.h(a.Ca,d.k({path:"/",domain:a.ea.site.domain,secure:a.ea.site.secure,encode:a.ea.encode},a.xa||{}))};b.Ca=a;b.ea=i;b.xa=o;return b};var T={};h.pa=function(a,b){var c=T[a];if(c!=s)return c;return c=T[a]=new b};d.n.Ka={};n=d.n.Ka;n.Mb=function(a,b){var c,f,e;d.l(a.length)||(a=[a]);
c=0;for(f=a.length;c<f;c++){e=a[c];var m=e.className||"";if(!RegExp("\\b"+b+"\\b").test(m))e.className=(m==""?"":m+" ")+b}};n.fc=function(a,b){var c,f,e;d.l(a.length)||(a=[a]);c=0;for(f=a.length;c<f;c++){e=a[c];if(e.className)e.className=e.className.replace(RegExp("\\b"+b+"\\b"),"")}};n.Ya=function(a,b){if(a){d.l(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var f in b)if(f){"zIndex".indexOf(f)==-1&&(typeof b[f]=="number"&&f!="opacity")&&(b[f]=b[f]+"px");a[c].style[f]=b[f]}}return a};n.Ob=function(a,
b){if(a){d.l(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var f in b)a[c].setAttribute(f,b[f])}return a};var X=n.Ya;n.outerHTML=function(a){if(d.l(a.outerHTML))return a.outerHTML;var b={TEXTAREA:r},c={HR:r,BR:r,IMG:r,INPUT:r},f=[],e="",m=a.nodeName;switch(a.nodeType){case 1:e=e+"<"+m.toLowerCase();if(b[m])switch(m){case "TEXTAREA":for(b=0;b<a.attributes.length;b++)if(a.attributes[b].nodeName.toLowerCase()!="value")e=e+(" "+a.attributes[b].nodeName.toUpperCase()+'="'+a.attributes[b].nodeValue+
'"');else var g=a.attributes[b].nodeValue;e=e+">"+g+("</"+m+">")}else{for(b=a.attributes.length-1;b>=0;b--){g=a.attributes[b].nodeName.toLowerCase();"style,class,id".indexOf(g.toLowerCase())>-1&&(e=e+(" "+g+'="'+a.attributes[b].nodeValue+'"'))}e=e+">";if(!c[m]){e=e+a.innerHTML;e=e+("</"+m.toLowerCase()+">")}}break;case 3:e=e+a.nodeValue;break;case 8:e=e+("<\!--"+a.nodeValue+"--\>")}f.push(e);return f.join("")};l.Ja=function(){function a(a){return c.toLowerCase().indexOf(a.toLowerCase())>-1}var b=
{g:"",j:"",version:0,mb:r,ra:0},c=b.sa=g.navigator.userAgent;if(/Opera[\/\s](\d+\.\d+)/.test(c))b.j="Opera";else if(/MSIE (\d+\.\d+)/.test(c))b.j="IE";else if(/Navigator[\/\s](\d+\.\d+)/.test(c))b.j="Netscape";else if(/Chrome[\/\s](\d+\.\d+)/.test(c))b.j="Chrome";else if(/Safari[\/\s](\d+\.\d+)/.test(c)){b.j="Safari";/Version[\/\s](\d+\.\d+)/.test(c);b.version=new Number(RegExp.$1)}else if(/Firefox[\/\s](\d+\.\d+)/.test(c))b.j="Firefox";if(a("Windows"))b.g="Windows";else if(a("OS X"))b.g="Mac";else if(a("Linux"))b.g=
"Linux";else if(a("Mac"))b.g="Mac";if(a("Android"))b.g="Android";else if(a("iPod"))b.g="iPod";else if(a("iPad"))b.g="iPad";else if(a("iPhone"))b.g="iPhone";else if((a("blackberry")||a("playbook")||a("BB10"))&&a("applewebkit"))b.g="Blackberry";else if(a("Windows Phone"))b.g="Winphone";else if(a("Kindle"))b.g="Kindle";else if(a("Silk"))b.g="Kindle";else if(a("BNTV250"))b.g="Nook";else if(a("Nook"))b.g="Nook";if(b.g=="")b.g=g.orientation!=o?"Mobile":"Other";b.bc="Android,iPod,iPad,iPhone,Blackberry,Winphone,Kindle,Mobile".indexOf(b.g)>
-1;if(b.j=="")b.j="Unknown";else if(!b.Va||b.Va==0){b.version=parseFloat(new Number(RegExp.$1));b.ra=b.j=="IE"?b.version>6&&b.version<10?!a("Trident")&&b.version==7?7:a("Trident/5.0")&&b.version<=9?9:a("Trident/4.0")&&b.version<9?8:b.version:b.version:b.version}if(a("Android 2"))b.mb=w;return b};var t=l.Ja();l.f={};l.f.A={};l.f.L=function(a,b,c,f){var e=l.f.A;if(a){e[b]||(e[b]=[]);e[b].push({aa:a,M:c});if(b=="unload"){if(d.l(d.K)){d.K.push(c);return}d.K=[]}b!="propertychange"&&a.addEventListener?
a.addEventListener(b,c,!f):a.attachEvent&&a.attachEvent("on"+b,c)}};l.f.Hb=function(a,b,c,f,e){var g=l.f;if(e){if(a.getAttribute("_fsr"+b))return w;a.setAttribute("_fsr"+b,"true")}else if(e=g.A[b])for(g=e.length-1;g>=0;g--){if(d.t)try{e[g].aa.toString()}catch(h){e.splice(g,1);continue}if(e[g].aa==a&&(f||e[g].M==c))return w}l.f.L(a,b,c)};l.f.Ib=function(a,b,c){l.f.L(a,b,c,r)};l.f.Sa=function(a,b,c){try{b!="propertychange"&&a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+
b,c)}catch(d){}};var D=l.f.L;l.f.La=function(){for(var a=d.K.length-1;a>=0;a--)try{d.K[a].call()}catch(b){}d.Fa(d.K);l.f.Oa();d.Y()};D(g,"unload",l.f.La);l.f.Oa=function(){if(d){var a=l.f,b;for(b in a.A){for(var c=a.A[b],f={};f=c.pop();){a.Sa(f.aa,b,f.M);d.Fa(f)}delete a.A[b]}}};l.f.S=function(){this.J=[]};l.f.S.prototype.Ab=function(a){this.J[this.J.length]={tb:w,M:a}};l.f.S.prototype.C=function(){for(var a=0;a<this.J.length;a++){var b=this.J[a];b.M.apply(this,arguments);if(b.tb){this.J.splice(a,
1);a--}}};var I=l.f.S,D={width:"1",height:"1",id:"_"+(""+Math.random()).slice(9),allowfullscreen:r,allowscriptaccess:"always",quality:"high",version:[3,0],rb:s,cb:s,la:w,Wa:w};g.attachEvent&&g.attachEvent("onunload",function(){__flash_unloadHandler=y();__flash_savedUnloadHandler=y()});var M=d.k(d.Sb,{Qb:D,hb:function(){var a,b;try{b=navigator.plugins["Shockwave Flash"].description.slice(16)}catch(c){try{b=(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"))&&a.GetVariable("$version")}catch(d){try{b=
(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"))&&a.GetVariable("$version")}catch(e){}}}return(b=/(\d+)[^\d]+(\d+)[^\d]*(\d*)/.exec(b))?[b[1],b[3]]:[0,0]},U:function(a){if(a===s||a===o)return s;var b=typeof a;b=="object"&&a.push&&(b="array");switch(b){case "string":a=a.replace(RegExp('(["\\\\])',"g"),"\\$1");a=a.replace(/^\s?(\d+\.?\d*)%/,"$1pct");return'"'+a+'"';case "array":return"["+V(a,function(a){return M.U(a)}).join(",")+"]";case "function":return'"function()"';case "object":var b=[],
c;for(c in a)a.hasOwnProperty(c)&&b.push('"'+c+'":'+M.U(a[c]));return"{"+b.join(",")+"}"}return(""+a).replace(/\s/g," ").replace(/\'/g,'"')},Ub:function(a,b){var a=d.k({},a),c='<object width="'+a.width+'" height="'+a.height+'" id="'+a.id+'" name="'+a.id+'"';if(a.Wa)a.src=a.src+((a.src.indexOf("?")!=-1?"&":"?")+Math.random());c=a.la||!d.t?c+(' data="'+a.src+'" type="application/x-shockwave-flash"'):c+' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"';c=c+">";if(a.la||d.t)c=c+('<param name="movie" value="'+
a.src+'" />');a.width=a.height=a.id=a.la=a.src=s;a.rb=a.version=a.cb=s;for(var f in a)a[f]&&(c=c+('<param name="'+f+'" value="'+a[f]+'" />'));f="";if(b){for(var e in b)if(b[e]){var g=b[e];f=f+(e+"="+(/function|object/.test(typeof g)?M.U(g):g)+"&")}f=f.slice(0,-1);c=c+('<param name="flashvars" value=\''+f+"' />")}return c+"</object>"},isSupported:function(a){return B[0]>a[0]||B[0]==a[0]&&B[1]>=a[1]}}),B=d.ma=M.hb();d.ib=B!=s&&0<B.length&&0<parseFloat(B[0]);d.ib||(B=d.ma=[0,0]);var J={};d.stringify=
function(a,b,c){var d;if(g.Prototype){d=Array.prototype.toJSON;delete Array.prototype.toJSON}if(!g.JSON||typeof g.JSON.stringify!=="function"){var e;E=q="";if(typeof c==="number")for(e=0;e<c;e=e+1)E=E+" ";else typeof c==="string"&&(E=c);if((x=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("_4c.stringify");a=L("",{"":a})}else a=g.JSON.stringify(a,b,c);if(g.Prototype)Array.prototype.toJSON=d;return a};var Q=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
O=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,q,E,W={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},x;g.JSON?J=g.JSON:function(){function a(a){return a<10?"0"+a:a}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+
":"+a(this.getUTCSeconds())+"Z":s};Boolean.prototype.toJSON=function(){return this.valueOf()};Number.prototype.toJSON=function(){return this.valueOf()};String.prototype.toJSON=function(){return this.valueOf()}}if(typeof J.parse!=="function")J.parse=function(a,c){function d(a,b){var e,g,h=a[b];if(h&&typeof h==="object")for(e in h)if(Object.prototype.hasOwnProperty.call(h,e)){g=d(h,e);g!==o?h[e]=g:delete h[e]}return c.call(a,b,h)}var e,a=""+a;Q.lastIndex=0;Q.test(a)&&(a=a.replace(Q,function(a){return"\\u"+
("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){e=(new Function("return "+a))();return typeof c==="function"?d({"":e},""):e}throw new SyntaxError("JSON.parse");}}();l.Jb=J;n.Na={Lb:{}};try{Array.prototype.slice.call(document.getElementsByTagName("html")),makeArray=function(a){return Array.prototype.slice.call(a)}}catch($){}var Y=
n.Na.hc=function(a,b,c){b=b||p;if(b.querySelectorAll&&(!d.t||!(t.version<=8&&a.indexOf("nth")>-1)))return S(b.querySelectorAll(a));if(!c&&g.$&&!g.Prototype)return g.$(a,b);for(var a=a.split(","),c=[],f=a.length-1;f>=0;f--){var e=a[f].replace(/^\s\s*/,"").replace(/\s\s*$/,"").replace(/\*=/g,"=").replace(/\>/g," > ").replace(/\s+/g," ");if(e.indexOf(" ")>-1){for(var e=e.split(" "),h=[b],i=w,j=0;j<e.length;j++)if(e[j]==">")i=r;else{for(var k=[],l=h.length-1;l>=0;l--)k=k.concat(R(e[j],h[l],i));h=k;i=
w}c=c.concat(d.Za(h))}else c=c.concat(R(e,b))}return c};h.h=function(a,b){a||(a="STORAGE");this.ca=a.replace(/[- ]/g,"");this.H=b||{};this.data={};this.Qa=new I;this.zb=4E3};h.h.prototype.set=function(a,b){this.T();this.o[a]=b;this.W()};h.h.prototype.get=function(a){this.T();return a?this.o[a]:this.o};h.h.prototype.Y=function(a){this.T();delete this.o[a];this.W()};h.h.prototype.nb=function(){this.o={};var a=this.H.duration;this.H.duration=-1;this.W();a?this.H.duration=a:delete this.H.duration};h.h.prototype.T=
function(){this.o={};try{var a=h.h.I(this.ca);if(a&&a.length>0){this.o=J.parse(a);if(!d.l(this.o))this.o={}}}catch(b){this.o={}}};h.h.prototype.W=function(){var a=d.stringify(this.o);this.ca.length+d.N(a).length>this.zb&&this.Qa.C(this);h.h.write(this.ca,a,this.H)};h.h.I=function(a){return(a=g.document.cookie.match("(?:^|;)\\s*"+d.bb(a)+"=([^;]*)"))?d.X(a[1]):s};h.h.write=function(a,b,c){var b=!c||!d.l(c.encode)||c.encode?d.N(b):b,a=d.N(a),f;for(f in c)if(c[f]){var e=c[f],b=b+(";"+(f==="duration"?
"expires":f));switch(f){case "duration":b=b+("="+(new Date(d.now()+e*d.na)).toGMTString());default:b=b+("="+e)}}g.document.cookie=a+"="+b;return a.length+b.length+2};h.h.nb=function(a,b){h.h.write(a,"",d.k(b,{duration:-1}))};h.h.Yb=y();h.h.isSupported=function(){return r};j.s={};j.s.set=function(a,b,c,d){c=K(d);c[1][a]=b;c[0].set("cp",c[1])};j.s.get=function(a,b){return K(b)[0][a]};j.s.wa=function(a,b){var c=K(b);delete c[1][a];c[0].set("cp",c[1])};j.s.append=function(a,b,c,d){d=K(d);d[1][a]=d[1][a]?
d[1][a]+","+b:b;if(c){b=d[1][a].split(",");c=b.length>c?b.length-c:0;d[1][a]=b.splice(c,b.length-1-c+1).join()}d[0].set("cp",d[1])};j.s.r=function(a){var a=a||h.e(),b=a.get("sd");d.l(b)||(b=a.get("cd"));b=i.ia[b];a={browser:t.j+" "+t.version,os:t.g.match(/ipod|ipad|iphone/i)?"iOS":t.g,pv:a.get("pv"),url:u(a,"c"),entry:u(a,"ep"),ref_url:u(a,"ru"),locale:u(a,"l"),site:u(i.site.name),section:u(b.section),referrer:u(a,"r"),terms:u(a,"st"),sessionid:u(a,"rid"),replay_id:u(a,"mid"),flash:d.ma.join(".")};
t.g.match(/android|ipod|ipad|iphone|blackberry|firefox/i)&&(a.screen=screen.width+"x"+screen.height);if(v.meta.user_agent)a.user_agent=t.sa;if(v.analytics.google_local||v.analytics.google){var c=h.h.I("__utma"),b=h.h.I("__utmz");if(c&&c!=""){c=c.split(".");a.first=c[2];a.last=c[3];a.current=c[4];a.visits=c[5]}if(b&&b!=""){var f,c=[];f=["utmgclid","utmcsr","utmccn","utmcmd","utmctr"];for(var e=0;e<f.length;e++)c.push(RegExp(f[e]+"=([^\\|]*)"));if(b.match(c[0])){a.source="Google";a.campaign="Google Adwords";
a.medium="cpc"}else{if(f=b.match(c[1]))a.source=f[1];if(f=b.match(c[2]))a.campaign=f[1];if(f=b.match(c[3]))a.medium=f[1]}if(f=b.match(c[4]))a.keyword=f[1]}}b=h.e("cp");c=h.e("meta");a=d.k({},b||{},a||{},c||{});return l.r(a,"cpp")};n=j.s;g.FSR.CPPS=n;n.set=n.set;n.get=n.get;n.erase=n.wa;n.append=n.append;D={};g.ForeSee=D;D.CPPS=n;n.fsr$set=n.set;n.fsr$get=n.get;n.fsr$erase=n.wa;n.fsr$append=n.append;j.i={};j.i.F=function(){var a,b=v.analytics.google_remote;if(b){var c=i.site.domain;b[c]&&(a=b[c])}return a};
j.i.r=function(a){var b={},c=j.i.F();if(c){b.domain="."+i.site.domain;b.id=c.id;b.name=c.name;b.event=a}return l.r(b,"ga")};j.i.ya=function(a){var b,c=j.i.F();c&&(b=c.events[a]);return b};j.i.fireEvent=function(a){var b=j.i.F();if(b){g._gaq=g._gaq||[];(a=j.i.ya(a))&&g._gaq.push(["_trackEvent","foresee survey",a,b.name])}};j.i.fb=function(a){var b=a;j.i.F()&&g._gat&&(b=g._gat._getTrackerByName()._getLinkerUrl(a));return b};j.i.kb=function(){var a=j.i.F();if(a){g._gaq=g._gaq||[];g._gaq.push(["_setAccount",
a.id]);g._gaq.push(["_setDomainName","."+i.site.domain]);g._gaq.push(["_trackPageview"]);a=document.createElement("script");a.type="text/javascript";a.async=r;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}};j.p={};j.p.Cb={host:"survey.foreseeresults.com",path:"/survey",url:"/display"};j.p.dc={host:"i.4see.mobi",path:"/e",url:"/initialize"};j.p.cc={host:"i.4see.mobi",
path:"/e",url:"/recordHeartbeat"};j.p.ua={host:"controller.4seeresults.com",path:"/fsrSurvey",url:"/OTCImg",Bb:3};j.p.event={host:"events.foreseeresults.com",path:"/rec",url:"/process"};j.p.domain={host:"survey.foreseeresults.com",path:"/survey",url:"/FSRImg",Bb:3};j.p.gc={host:"replaycontroller.4seeresults.com",path:"/images",enabled:r};d.w(function(){i.siteid=l.fa("siteid");i.site=i.sites[i.siteid];i.site.name||(i.site.name=l.fa("name"));i.site.domain||(i.site.domain=l.fa("domain"));i.site.domain==
"default"&&(i.site.domain=s);for(var a=["files","js_files","image_files","html_files","css_files","swf_files"],b=0;b<a.length;b++){var c=a[b];i.site[c]||i[c]&&(i.site[c]=i[c])}});d.d=function(a){d.k(this,{options:d.k({},a),Ha:w,q:w,B:s,z:s,P:s,m:s});i.controller=this;this.Gb()};d.d.loaded=new I;d.d.Ia=new I;d.d.Da=new I;d.d.Ga=new I;d.d.prototype.Gb=function(){if(d.d.R.ba)for(var a=[["loaded",d.d.loaded],["initialized",d.d.Zb],["trackerCanceled",d.d.Ia],["qualifierShown",d.d.Da],["surveyShown",d.d.Ga]],
b=0;b<a.length;b++){var c=a[b];d.v(d.d.R.ba[c[0]])&&c[1].Ab(d.d.R.ba[c[0]])}};d.d.prototype.load=function(){if(t.j!="Chrome"&&!(t.j=="Firefox"&&t.version>=4)&&!(t.j=="Safari"&&t.version>=5)){var a=document.getElementById("hide");if(a)a.style.display="block"}if(this.q)return this;this.q=r;j.qb(function(a){return function(){a.xb()}}(this),i.embedded)};d.d.prototype.xb=function(){d.d.loaded.C();h.e("t",1);j.i.kb();this.yb();this.B=this.Ea();this.P=d.now();this.z=setInterval(function(a){return function(){a.ua()}}(this),
500)};d.d.prototype.Eb=function(){if(this.q){h.e("t",0);clearInterval(this.z);this.q=w;if(!this.Ha){h.e("rc",r);d.d.Ia.C(this.m,h.e());j.log("201")}}};d.d.prototype.ua=function(){var a=this.Ea(),b=h.e("fo")||0,c=h.e("to")||v.tracker.timeout,f=v.tracker.pause||6;if(a==this.B){try{if(g.opener.document)return}catch(e){}if(this.paused!="1"){if((d.now()-this.P)/1E3>=c){clearInterval(this.z);this.ga()}}else if((d.now()-this.P)/1E3>f){clearInterval(this.z);this.ga()}}else if(b!=0){clearInterval(this.z);
this.ga(b!=1)}else{this.B=a;this.P=d.now();this.paused=0;if(this.B=="paused"||this.B=="suspended")this.paused=1}};d.d.prototype.ga=function(a){this.Ha=r;this.Xa();this.ob(a||this.m.pop.pu)};d.d.prototype.Xa=function(){var a=h.e(),b=a.get("sd");d.l(b)||(b=a.get("cd"));a=i.ia[b];a.idx=b;a.survey=d.G(v.survey,a.survey||{});a.qualifier=d.G(v.qualifier,a.qualifier||{});a.pop=d.G(v.pop,a.pop||{});a.tracker=d.G(v.tracker,a.tracker||{});this.m=a};d.d.prototype.ob=function(a){h.e("s",1);this.m.pop.what!="qualifier"?
this.vb(a):this.ub(a)};d.d.prototype.vb=function(a){d.d.Ga.C(this.m,h.e());j.log("400",h.e("c")||"");var b=j.p.Cb,c=this.m.survey,f=(g.screen.width-c.width)/2,e=(g.screen.height-c.height)/2,m=d.Z(),n=b.host,p=b.path,k=new Date-0+"_"+Math.round(Math.random()*1E13),q=l.hash(k),t=h.e("c")||"",q={sid:j.gb(this.m,this.m.pop.later),cid:i.id,pattern:t,a:k,b:q,c:d.na,version:i.version},t=j.s.r(),k=j.i.r(j.i.ya("survey_shown")),q=l.r(q),b=m+"//"+n+p+b.url+"?"+q+"&"+t;k&&k!=""&&(b=b+"&"+k);b=j.i.fb(b);this.pop(b,
f,e,c.width,c.height,a)};d.d.prototype.ub=function(a){d.d.Da.C(this.m,h.e());j.log("300",h.e("c")||"");var b=this.m.qualifier;this.page(b);var c=(g.screen.width-b.width)/2,f=(g.screen.height-b.height)/2,e=l.va(i.site,"html_files")+(b.url.pop||b.url),m={siteid:i.siteid,name:i.site.name,domain:i.site.domain};this.m.pop.later&&(m.when=this.m.pop.later);m=l.r(m);this.pop(e+("?"+m),c,f,b.width,b.height,a)};d.d.prototype.pop=function(a,b,c,d,e,j){var i=this.m.tracker;if(!j&&t.j==="Chrome"&&i.alert&&i.alert.enabled){this.page(i.alert);
alert(i.alert.message)}setTimeout(function(){g.moveTo(b,c);g.resizeTo(d,e);if(j){g.blur();try{g.opener.focus()}catch(i){}}else g.focus();h.e().Y("t");clearInterval(this.z);p.location.href=a},0)};d.d.prototype.page=function(a){var b=h.e("l");if(b)for(var c=a.locales||[],d=0,e=c.length;d<e;d++)if(c[d].locale==b){c[d].url&&(a.url=c[d].url);c[d].message&&(a.message=c[d].message);c[d].accept&&(a.accept=c[d].accept);c[d].decline&&(a.decline=c[d].decline);c[d].width&&(a.width=c[d].width);c[d].height&&(a.height=
c[d].height);break}};d.d.prototype.Ea=function(){return h.h.I(h.za("fsr.a"))};d.d.prototype.yb=function(){p.cookie="fsr.a"+(i.site.cookie?"."+i.site.cookie:"")+"="+d.now()+";path=/"+(i.site.domain?";domain="+i.site.domain+";":";")+(i.site.secure?"secure":"")};d.w(function(){(new d.d).load();l.f.L(g,"unload",function(){i.controller.Eb()})});d.d.R={ba:{loaded:y(),trackerCanceled:y(),qualifierShown:y(),surveyShown:y()}}})(window,$$FSR);})({});
}
// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
